version: "3.7"

services:
  server:
    build: Server/
    ports:
      - "8080:8080"
    networks:
    - backend
  client_mobile:
    build: Application/
    volumes:
      - common:/apk
  client_web:
    build: Web/
    depends_on:
      - server
      - client_mobile
    ports:
      - "8081:8081"
    networks:
    - frontend
    volumes:
      - common:/apk

networks:
  frontend:
  backend:

volumes:
  common: